name: Prepare release

on:
  workflow_dispatch:
    inputs:
      version_part:
        description: The part of the version to update (patch, minor or major)
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: minor

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Bump the version number
        id: bump_version
        run: |
          python ./.github/scripts/bump_version.py ${{ github.event.inputs.version_part }}
          echo "package_version=$(pdm show --version)" >> "$GITHUB_OUTPUT"
      - name: Update the CHANGELOG according to 'Keep a Changelog' guidelines
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: ${{ steps.bump_version.outputs.package_version }}
      - name: Create a new release branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b release/${{ steps.bump_version.outputs.package_version }}
          git commit -am "Bump version and CHANGELOG for release ${{ steps.bump_version.outputs.package_version }}"
          git push -u origin release/${{ steps.bump_version.outputs.package_version }}
      - name: Open a PR to merge the release to main
        id: open_pr
        uses: vsoch/pull-request-action@1.0.24
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
          PULL_REQUEST_BRANCH: main
          PULL_REQUEST_FROM_BRANCH: release/${{ steps.bump_version.outputs.package_version }}
          PULL_REQUEST_TITLE: "Release ${{ steps.bump_version.outputs.package_version }}"
          PULL_REQUEST_BODY: "Bump version and CHANGELOG for next release."
