name: Python Publish Workflow
on:
  workflow_run:
    workflows:
      - "Linting and Tests"
    branches:
      - release/**
    types:
      - completed

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: build
        id: build
        run: |
          pdm build
          echo "RELEASE_FILE_WHL=$(ls dist/*.whl)" >> "$GITHUB_OUTPUT"
          echo "RELEASE_FILE_TAR=$(ls dist/*.tar.gz)" >> "$GITHUB_OUTPUT"
          echo "RELEASE_VERSION=$(pdm show --version)" >> "$GITHUB_OUTPUT"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ${{ steps.build.outputs.RELEASE_FILE_WHL }}
            ${{ steps.build.outputs.RELEASE_FILE_TAR }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.build.outputs.RELEASE_VERSION }}
      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.8.6
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
